### ISSUE TITLE
no settings button option

### ISSUE THREAD

**Issue by Bappy1988** [AntonyCorbett/OnlyR#10]
Would it be possible to have a command line switch that removes the settings button? In some installations users with limited knowledge have been known to tinker with settings and thus disrupt the system for later users...

Happy to write a patch and send in a PR 
Thanks :)

**Comment by AntonyCorbett** [comment]
@Bappy1988 - thanks for your feedback. I'd be more than happy to receive a pull request,

**Comment by AntonyCorbett** [comment]
Now available via commandline option "--nosettings"
