### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by mrndepth** [AntonyCorbett/OnlyR#12]
My congergation is just starting to use JW Lib. We still have to teach some of the older ones what to do. The younger ones are picking it up right away. The org. SoundBox had many features that was left out of Only-R. Under the Record tab, you can start a new tract. You cant do that in Only-R. In soundBox, you could add MP3 Tags. You can't do that in only-r. SoundBox has a Copy tag. Only-R don't. These are very important features. Currently, we are running both SoundBox and JW Lib at the same time. I can only hope that Only-R is fixed and that SoundBox don't stop working when support runs out.

**Comment by AntonyCorbett** [comment]
@mrndepth thanks for your feedback. SoundBox won't stop working in 2019 unless it meets with OS incompatibilities. Regarding the features you mention, I have deliberately kept the "Only" apps lightweight with attention focused on what I understand to be key functionality (for the majority of users). I don't know what features JWL will eventually offer so I hope you'll understand the reasons for my stance.

**Comment by JonMcFly** [comment]
To start a new track, just press stop, then press again to record another track.  Click-Click, simple.

**Comment by Blann** [comment]
And copying to removable media is fairly straightforward

**Comment by AntonyCorbett** [comment]
Closing, but would welcome specific feature requests (1 issue per item). Note that "Copy" function is now available in the latest draft release.
