### ISSUE TITLE
Doesn't start after 1803 windows update

### ISSUE THREAD

**Issue by mcrally** [AntonyCorbett/OnlyR#13]
The software doesn't start anymore after windows 10 home edition update.
No error on screen after clicking on it.

I tried many times to uninstall and reinstall using last 1.0.0.20 version and the previous also. Nothing changes. It doesn't start.

This is the error I get from Windows Event Log

Applicazione: OnlyR.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: System.BadImageFormatException

Nome dell'applicazione che ha generato l'errore: OnlyR.exe, versione: 1.0.0.20, timestamp: 0x5a66d2c0
Nome del modulo che ha generato l'errore: KERNELBASE.dll, versione: 10.0.17134.165, timestamp: 0xfa43f4b2
Codice eccezione: 0xe0434352
Offset errore 0x0010ddc2
ID processo che ha generato l'errore: 0x142c
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d420daf8ea817e
Percorso dell'applicazione che ha generato l'errore: C:\Program Files (x86)\OnlyR\OnlyR.exe
Percorso del modulo che ha generato l'errore: C:\WINDOWS\System32\KERNELBASE.dll
ID segnalazione: ccc9ff3f-5b30-4b55-a999-86be01d049cf
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:

**Comment by AntonyCorbett** [comment]
It's most likely caused by Windows wrongly updating the video driver. Please check the video driver is up to date, referring to the manufacturer's website to get the latest one. I can confirm that OnlyR works fine on 1803.
