### ISSUE TITLE
Need "pause" in record mode.

### ISSUE THREAD

**Issue by XDefender** [AntonyCorbett/OnlyR#15]
Hello Antony.

If possible, please add in OnlyR  "pause" in record mode.

Great thanks!

**Comment by AntonyCorbett** [comment]
@XDefender thanks for your suggestion. There would have to be a compelling use case for a pause function, because it would complicate the UI. Do you have a particular use case in mind?

**Comment by AntonyCorbett** [comment]
@XDefender closing for now. Please feel free to reopen the issue with further comments.

**Comment by AlainDema** [comment]
Salve la funzione di mettere in pausa (e non stoppare) permette di non registrare le preghiere come da disposizioni o annunci che NON devono essere memorizzati senza però dover rinunciare anche al cantico iniziale per chi non può purtroppo essere presente in sala. Sarebbe utile magari l'avvio automatico della registrazione ad inizio adunanza.
