### ISSUE TITLE
Possibility to add MP3 tags

### ISSUE THREAD

**Issue by Hi-there-how-are-u** [AntonyCorbett/OnlyR#16]
It would be great if you could add the same mp3 tags as in Soundbox. Yesterday one publisher asked for a specific speech from june but did not know exact date. I did not have the schedule left for that month so I solved it by giving all the speeches for that month. This is not a must have feature but it would be really appreciated if you could add that, no hurry whatsoever and I understand if you do not have the time to do it. Thanks for great software!

**Comment by AntonyCorbett** [comment]
@Hi-there-how-are-u Thanks for your suggestion. I have deliberately kept the "Only" apps lightweight with attention focused on what I understand to be key functionality (for the majority of users). So I think it's unlikely to be implemented - sorry. I'll keep the issue listed for a few weeks.

**Comment by AntonyCorbett** [comment]
No further comments so closing for now

**Comment by naveugene** [comment]
Hi Antony! In SoundBox this function (to add MP3 tags before recording) was very necessary! But, because it is inconvenient to use Sounbox from 1st January 2019, we really miss this feature in OnlyR. Could you please add this ability to OnlyR all the same?
