### ISSUE TITLE
App screen position 

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyR#17]
Not a big issue... however when OnlyR is loaded/opened it will display the app on the top right of my screen; if I change/shift where it is positioned on the screen (lower left), close the app then re-open it will revert to a default position (upper right) on the screen again.

I am using version 1.0.0.23 

I was hoping that since I am using Windows Task Scheduler to open the app automatically and start recording, that it would position on the screen in a particular position (lower left or wherever) to fit in with other Only'X' apps/programs to fit within the screen 'real estate'.

[i.postimg.cc/DZh8WTPB/screenshot_555.png](url)

**Comment by AntonyCorbett** [comment]
@Chipperchap thanks for feedback - now fixed in latest release.

**Comment by Chipperchap** [comment]
Confirming that it is fixed.  Thank you so much @AntonyCorbett
