### ISSUE TITLE
Ageing out recordings

### ISSUE THREAD

**Issue by mrSundberg** [AntonyCorbett/OnlyR#19]
With the recent news and hype of GDPR and subsequent clarification of the intent and implementation for the Kingdom Halls a function to age out recordings is needed.

The document describing this talks about a shelf life of 7 days.

Is this a feature that can be implemented? Or should I look for a different solution? There is a couple of alternatives, a script for ageing backup files can be customized.

https://gallery.technet.microsoft.com/scriptcenter/powershell-script-to-0c11660b

But it is always easier to have a single tool that already manages the recordings to do this.

Perhaps by a single radio button in settings to turn on and off GDPR compliance, or a setting to specify how many days to keep the recordings, with a 0 (zero) to keep forever.
Alternatively there can be a slider between forever and a week meaning 7 days.

**Comment by josslamberti** [comment]
@mrSundberg what clarification are you talking about?

> With the recent news and hype of GDPR and subsequent clarification of the intent and implementation for the Kingdom Halls a function to age out recordings is needed.

Is there any official documentation we can refer to on this matter?

**Comment by mrSundberg** [comment]
Thanks for asking. 

At least in Sweden there came a document on jw.org explaining what data is being used and what measures were taken to comply with the law. It's available for the elders under the name crpa.

Best regards mrSundberg

⁣Skickat från BlueMail ​

Den 23 okt. 2018 10:29, kI 10:29, josslamberti <notifications@github.com> skrev:

**Comment by AntonyCorbett** [comment]
@mrSundberg Please see latest pre-release where this is now implemented.
