### ISSUE TITLE
Recording does not stop

### ISSUE THREAD

**Issue by buteman** [AntonyCorbett/OnlyR#21]
**Describe the bug**
I set up OnlyR to start recording on startup.
When it started the recording stayed at 00:00 even though it said it was recording.
I clicked to stop recording. It displayed Stopping but never stopped even after several minutes.
I could not close it except via task manager.
I uninstalled it but when I re-installed it the setting had not been removed by the uninstall so it did the same again.

**To Reproduce**
Start Onlyr
set it up to record on starting.
run task manager to kill it.

**Expected behavior**
That the recording time would increment and it would stop recording when asked to do so.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
windows 10 pro
 - Other important information about your environment

**Comment by AntonyCorbett** [comment]
@buteman Thanks for your report. It sounds like there may be no default recording device. Please would you send me a copy of your latest log file?

 MyDocuments\OnlyR\Logs

**Comment by buteman** [comment]
Hi Antony,
This is the content of the log from my attempt just a few minutes ago.

"2018-10-22 10:36:23.689 +01:00 [Information] ==== Launched ====
2018-10-22 10:36:38.565 +01:00 [Information] Start requested
2018-10-22 10:36:38.630 +01:00 [Information] New candidate =
RecordingCandidate { RecordingDate: 10/22/2018 00:00:00, TrackNumber: 1,
TempPath:
"C:\Users\norma\AppData\Local\Temp\OnlyR\Recordings\2904b9c6472c48db929d09ce35b38669.mp3",
FinalPath:
"C:\Users\norma\OneDrive\Documents\OnlyR\2018\10\2018-10-22\Monday 22
October 2018 - 001.mp3" }
2018-10-22 10:36:42.282 +01:00 [Information] Started recording
2018-10-22 10:37:05.286 +01:00 [Information] Stop requested"
If I knew where it keeps it's config file I think I could delete it and
then perhaps adjust the settings. At present I can do nothing other than
kill it with Task Manager as I have it set to start recording immediately
when it's launched.

**Comment by buteman** [comment]
I think it's gone wrong somewhere as it is trying to use \Users\norma
a user who doesn't exist. I have been examining it from my Linux partition
as I only use Windows for when I am testing stuff out for the Hall. I can
create a user structure on the windows partition and see if that fixes the
problem.

**Comment by buteman** [comment]
Well somehow that worked but strangely the loh shows it actually wrote to
the correct place
"2018-10-22 16:22:05.591 +01:00 [Information] ==== Launched ====
2018-10-22 16:30:30.760 +01:00 [Information] Start requested
2018-10-22 16:30:30.771 +01:00 [Information] New candidate =
RecordingCandidate { RecordingDate: 10/22/2018 00:00:00, TrackNumber: 1,
TempPath:
"C:\Users\norman\AppData\Local\Temp\OnlyR\Recordings\c6f8bb7b232b426a94facea352eae396.mp3",
FinalPath: "C:\Users\norman\Documents\OnlyR\2018\10\2018-10-22\Monday 22
October 2018 - 001.mp3" }
2018-10-22 16:30:31.981 +01:00 [Information] Started recording
2018-10-22 16:30:41.280 +01:00 [Information] Stop requested
2018-10-22 16:30:41.926 +01:00 [Information] Stopped recording
2018-10-22 16:30:41.981 +01:00 [Information] Copying
"C:\Users\norman\AppData\Local\Temp\OnlyR\Recordings\c6f8bb7b232b426a94facea352eae396.mp3"
to "C:\Users\norman\Documents\OnlyR\2018\10\2018-10-22\Monday 22 October
2018 - 001.mp3"
2018-10-22 16:31:36.533 +01:00 [Information] Settings changed and saved
2018-10-22 16:31:36.580 +01:00 [Information] ==== Exit ===="

**Comment by AntonyCorbett** [comment]
@buteman Thanks for the logs. OnlyR creates the recording in the user's system-defined temporary folder and then copies it to the user's system-defined documents folder on completion. If these were not reported correctly by Windows then it would account for the issue.
