### ISSUE TITLE
Recording not placed in FinalPath (presume shut down before close of app)

### ISSUE THREAD

**Issue by DanJermy** [AntonyCorbett/OnlyR#22]
A recording doesn't appear in FinalPath.

On inspection of log, It appears that 'stopped recording' and 'Copying' actions not undertaken - implying the AV brother didn't press stop on the recording before shutting down...

> 2018-11-15 18:58:48.171 +00:00 [Information] ==== Launched ====
> 2018-11-15 18:58:48.999 +00:00 [Information] Start requested
> 2018-11-15 18:58:48.999 +00:00 [Information] New candidate = RecordingCandidate { RecordingDate: 11/15/2018 00:00:00, TrackNumber: 1, TempPath: "C:\Users\Admin\AppData\Local\Temp\OnlyR\Recordings\b4a76a402a6444b58caca0efbdef17fa.mp3", FinalPath: "C:\Users\Admin\Documents\OnlyR\Recordings\2018\11\2018-11-15\Thursday 15 November 2018 - 001.mp3" }
> 2018-11-15 18:58:49.217 +00:00 [Information] Started recording

Do I just need to tick the "Allow close when recording" to mitigate this or does there need to be an alert warning the user that a recording is still running if a user initiates a shut down?

Apologies for the simplistic query

**Comment by DanJermy** [comment]
Side-note: I think we wanted to avoid the tick of 'allow close when recording' so as to ensure the app isn't accidentally closed mid-meeting.

**Alternative resolution:**
Could have an enhancement to the app to check logs and/or temp folder on launch for uncopied files and prompt user to confirm retrieval/copy action?

**Comment by AntonyCorbett** [comment]
@DanJermy If the "Allow close when recording" option is unchecked then OnlyR will _not_ allow a user to close the application in the normal way, i.e. when you click close or use Alt-F4 OnlyR will not close. It may be that Windows was shut down and the process explicitly aborted.
