### ISSUE TITLE
Window resize

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyR#23]
@AntonyCorbett will you consider to make the settings window adjustable like for OnlyM and OnlyT? The settings are a bit crowded in that small window. And also change the window title to "S o u n d B o x - O N L Y R" according to the other apps (and maybe to increase a bit the main window to fit the title)?

**Comment by AntonyCorbett** [comment]
@LvDaniel Implemented in latest pre-release

**Comment by LvDaniel** [comment]
@AntonyCorbett Thank you!
