### ISSUE TITLE
Burning OnlyR recordings to CDs

### ISSUE THREAD

**Issue by MDS201** [AntonyCorbett/OnlyR#25]
In our congregation some of the older ones in the congregation still like recordings of the meeting on a disc. 

Is there a simple way of burning recordings from OnlyR to a disc like CD-R?

**Comment by AntonyCorbett** [comment]
@MDS201 Not from OnlyR itself, but you can use other CD burning software. Let's leave this issue open as an enhancement and see if others want it built into OnlyR (like it was in SB 3.1).

**Comment by Blann** [comment]
Would be nice to have the option as long as it doesn’t complicate things – it’s useful on occasion.

**Comment by scottys94** [comment]
I also agree that this feature would be beneficial.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AntonyCorbett** [comment]
I'm afraid I will have to reject this feature request on the basis that CDs are used less and less, and there is a simple work-around (copy the MP3 to CD using Windows 10) for the cases where folks insist on using them.
