### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by Szynek007** [AntonyCorbett/OnlyR#26]
If is possible to add "Automatic Minimize to Tray" option?

We use OnlyR for automatic records. When app is start (windows task scheduler) app is on top in a desktop. After we have task scheduler to kill task. It will be very helpful to add option "automatic minimize to tray when start" because all operations with this options will be don't show for user.

**Comment by AntonyCorbett** [comment]
@Szynek007 Would it be sufficient to have OnlyR remember the minimized state, so that when next launched it runs minimized?

**Comment by Szynek007** [comment]
I think for our uses it will be better than now (if tray is too complicated)

**Comment by lazer321** [comment]
If you are using task manager, the following can be used to launch OnlyR minimized...

Program:  cmd.exe
Arguments:  /c start "" /min OnlyR.exe
Start in:  C:\Program Files (x86)\OnlyR

Of course, the start in folder should reflect the location of your OnlyR executable.

Hope that is helpful.
