### ISSUE TITLE
Copy function

### ISSUE THREAD

**Issue by AntonyCorbett** [AntonyCorbett/OnlyR#3]
Function to copy recordings to removable media (rather than having to open Windows Explorer and copy from there)

**Comment by pepekall** [comment]
A nice feature that Finnish "competitor" Theorec has is that when you plug in the USB, it regognizes it and asks to copy last meeting to the stick. That would be nice one. There is also a possibility to select some older meetings as well into the copy session.

**Comment by AntonyCorbett** [comment]
Added copy to removable media function in 1.0.0.23
