### ISSUE TITLE
Bug Localization

### ISSUE THREAD

**Issue by KovalevArtem** [AntonyCorbett/OnlyR#40]
![image](https://user-images.githubusercontent.com/36500228/61547972-36cf2d00-aa55-11e9-9a25-ae056b3f296c.png)
For some reason, the translated strings did not fall into the application (Version 1.0.0.29)
![image](https://user-images.githubusercontent.com/36500228/61548105-86155d80-aa55-11e9-96f1-44d9db5f9b33.png)

**Comment by AntonyCorbett** [comment]
@KovalevArtem The Russian translation shows this string in English. Please translate to Russian
