### ISSUE TITLE
Unsafe removal of portable drives

### ISSUE THREAD

**Issue by TizianoNoto** [AntonyCorbett/OnlyR#42]
**Describe the bug**
While testing OnlyR functions I pressed the button to save the recordings on a USB stick. After copying, the drive was ejected from the system even if another application was transferring files into it, causing some errors. Seems like OnlyR actually performs a forced removal.

**To Reproduce**
1. plug in a removable drive
1. make sure the drive is busy, e.g. by opening a Word document from it
1. press the "Save today's recording" button in OnlyR
1. the removable drive is ejected without confirmation

**Expected behavior**
Drive removal should fail if the drive is still in use by the system and, when successful, Windows should notify the user as usual.

**Desktop:**
 - Windows 10 version 1809
 - OnlyR version 1.0.0.29

**Comment by AntonyCorbett** [comment]
Addressed this in 1.0.0.32
Ejection does not work exactly as it does in Windows, but it checks to ensure that there are no open file handles before ejecting. @TizianoNoto - the above test may not work since Word may not have an open file handle. A better test is playing a video from the USB drive.
