### ISSUE TITLE
Pause recording button

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyR#56]
Hi Antony,
The installation of the pause button would help us a lot to not have to record sentences, songs and videos. This would help the recording files are not very large and we can send the meeting to WhatsApp to the brothers who could not attend. This APP only allows you to send audio files of up to 16 megabytes. WhatsApp is the APP that we use in our country.
Best regards.
Sergio.

**Comment by kq5m9** [comment]
Hi Sergio,

If I may make a suggestion:  You may wish to try dropping the bitrate down to 32 kbps. This should give you a file size of roughly 13.8 MB / hour. If you were do stop and restart your recording during the middle song, you would generate 2 files, both of which would be well under your limit of 16 MB. Granted at 32 kbps, the music would be intelligible but not wonderful. As to speech, the BBC is reported as recommending 64 kbps for podcasts, so 32 kbps would not be that bad.

Just a thought...

**Comment by AntonyCorbett** [comment]
See #15
