### ISSUE TITLE
Implementation of audio streaming through IceCast

### ISSUE THREAD

**Issue by tenisak** [AntonyCorbett/OnlyR#57]
Hi Antony!

Would it be possible to implement the audio streaming function through the IceCast server? (IceCast is the standard for Internet radio.) It would stream simultaneously with the recording. 

Many congregations in our cz/sk Branch use the IceCast server [jwstream.eu](https://www.jwstream.eu) It would be great to have both recording and streaming in one program. (It's just a client implementation, not a server.)

Streaming is quite easy, for example, using the Bass.net libraries from [un4seen.com](http://www.un4seen.com/bass.html) ([IceCast documentation here](http://bass.radio42.com/help/html/d32d5240-397e-3e64-a0a4-0ebd3176f929.htm)).

Thanks for your great work!
Tenisak

**Comment by AntonyCorbett** [comment]
Hi Tenisak

Thanks for the idea. I think this falls into the category of functionality that is already provided (officially or otherwise), so I'm reluctant to spend development time on it. I appreciate your feedback, and please comment furtrher if I've missed something.

Regards
Antony

**Comment by tenisak** [comment]
Hi Anthony,

thanks a lot for the reaction. I do not know that there is an official stream available on the territory of our Branch (Czech-Slovak). I think that if it were available, I would definitely know about it ;-) The only thing we use here is the above server. On the territory of your branch is available any official stream? Do you have a tip for an unofficial streaming server as well as streaming software?

Thanks a lot for your work,
Tenisak

**Comment by AntonyCorbett** [comment]
@tenisak thanks. Some languages (including English) have an official video stream for each meeting. This means elders can send a link to those unable to attend, If that's not available in your language, I understood from your comments that you have an existing solution - just not all in one.
