### ISSUE TITLE
Shutting pc down loses recording

### ISSUE THREAD

**Issue by AndyZBell** [AntonyCorbett/OnlyR#58]
**Describe the bug**
If the windows 10 pc is shut down during recording the recording is lost

**To Reproduce**
1. Start recording 
2. Shut down the pc
3. No recording is saved

**Expected behavior**
The app should refuse tj shut down and put up a modal dialogue asking if I want to save. Windows will then report that it can’t shut down and that gives me a chance to abort and save the work. Even better would be to stop the recording and save the recording...

 I’ve tried looking for the temporary recording file but this isn’t much use as we often don’t realise that a recording was lost until someone wants it - often weeks later. 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version 10
 - Other important information about your environment

**Comment by LvDaniel** [comment]
@AndyZBell have you tried to check the option "Allow close when recording"? It should save the recording.

**Comment by AndyZBell** [comment]
Yes. And it saves it when the app is closed, but not when windows is shut down...

I’ll check it again tomorrow...

Andy

**Comment by LvDaniel** [comment]
In my case I've scheduled a task (in Task Scheduler) to start OnlyR when the meeting starts (@ 19:00) and another task to close OnlyR 5 minutes after the meeting finishes (20:50 in my case). For closing you can use use "taskkill /IM OnlyR.exe" command (you need to have "Allow close when recording" option enabled in OnlyR). Also you can configure OnlyR to starts minimized.

**Comment by AndyZBell** [comment]
Thanks for the info. Someone had turned off the Allow app to close during recording. So that caused the problem.

I now have set up task schedules to automate it.

Many thanks.

Andy
