### ISSUE TITLE
Recording doesn’t save unless stop button pressed

### ISSUE THREAD

**Issue by manningcarl** [AntonyCorbett/OnlyR#60]
Firstly i would like to express my appreciation for all your apps!

Second:
If the PC is shut down without pressing stop on the app, the recording is not saved. I am making massive assumption of how the app is structured but perhaps its possible to either write the data to disk when a terminateprocess is received or its possible to block the shutdown like some other apps (E.G. MS Office apps) while an unsaved recording is still in memory.
This is different from the behaviour when task manager is used to End task, which saves the file correctly.
Windows 10 Pro version 1809 
ONLYR version 1.0.0.26

If you need any more info please ask.

**Comment by AntonyCorbett** [comment]
@manningcarl thanks. Yes, handling the SessionEnding event may help here

**Comment by AntonyCorbett** [comment]
Note that you can safely close the app (e.g. Ctrl-F4) so long as the relevant setting is enabled (see wiki)

**Comment by AntonyCorbett** [comment]
@manningcarl Now prevent a shutdown if recording.
