### ISSUE TITLE
Possible to record video

### ISSUE THREAD

**Issue by TIIGRUS** [AntonyCorbett/OnlyR#62]
Is it possible to record video from a camera?
And is there an opportunity to make a scheduled recording?
Thank you very much!

**Comment by TIIGRUS** [comment]
Or what can you recommend from a free meeting recording?

**Comment by AntonyCorbett** [comment]
@TIIGRUS OnlyR is for audio recording only. I assume you are asking about recording video from a camera connected directly to a Windows PC. "OBS" is the only video capture software I have experience with but it does a lot more than record so may be overkill for your application.

**Comment by TIIGRUS** [comment]
@AntonyCorbett There is no scheduler in OBS, as in Soundebox.

**Comment by AntonyCorbett** [comment]
@TIIGRUS Sorry I don't understand what you mean by "scheduler".

**Comment by TIIGRUS** [comment]
@AntonyCorbett I mean, determine the start time of the meeting and that the program starts recording automatically.

**Comment by AntonyCorbett** [comment]
@TIIGRUS This project page is for the "OnlyR" software not SoundBox 3.1 but thanks for clarification - I understand what you mean.

**Comment by TIIGRUS** [comment]
@AntonyCorbett  Thank you very much!
