### ISSUE TITLE
Error starting recording.

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyR#68]
Hi Antony,
A new user was created on the KH PC, and ONLYR does not start recording. The error message says that you cannot start recording.
What will be the cause of the problem?
With the other user it works perfect.

Best regards

Sergio

**Comment by lazer321** [comment]
Hi Sergio,

I'm not Antony, but I can give you a couple of suggestions of things to check until he gets a chance to get back to you. (Time zones and all)

You might want to check the settings and make sure you have a valid recording device selected and that your recordings folder is one that the new user can write to. This is especially true if your recording folder is set to a user folder for the other user. Besides that, the settings should be identical.

Just some thoughts. I hope they help.

             - Kevin.

**Comment by AntonyCorbett** [comment]
@gonzo041 The log file should indicate the reason. Perhaps you could send it please? See the Documents\OnlyR\Logs folder

**Comment by gonzo041** [comment]
Antony, I attached the file you requested.
[log-20200223.txt](https://github.com/AntonyCorbett/OnlyR/files/4246567/log-20200223.txt)

**Comment by AntonyCorbett** [comment]
@gonzo041 Thanks for the log file. Is your **Settings => Recording Device** specified correctly?

**Comment by gonzo041** [comment]
The recording device is correct. We use the input line of the sound board. On the other hand, the microphone's privacy settings were deactivated, so when I activated it, it started recording normally as it does with the other user. Was that the cause of the error?
I attach an image.
![Grabaciones](https://user-images.githubusercontent.com/41997628/75193310-bed88c00-5734-11ea-9fec-52d53d93ae2d.png)

**Comment by AntonyCorbett** [comment]
@gonzo041 oh yes, I'd forgotten about that. I'll try to add a check for it. Thanks, Antony

**Comment by gonzo041** [comment]
Thank you brother for your great help.
big hug.
Sergio.

**Comment by AntonyCorbett** [comment]
@gonzo041 Assuming this is resolved now so closing.
