### ISSUE TITLE
Multiple Congregations

### ISSUE THREAD

**Issue by averywebdesign** [AntonyCorbett/OnlyR#7]
Hi Anthony, any chance of a multiple congregations option on launch with corresponding folder hierarchy? Reason for request: for congregations using JW Library for videos & single log in (to stop the need to download JW Library videos multiple times for each user account)

**Comment by AntonyCorbett** [comment]
@averywebdesign  - there is already provision for this in OnlyR. Use the /id= command-line options. Create shortcuts on your desktop for each congregation and then modify the targets to include "/id=Cong1", "/id=Cong2", etc
