### ISSUE TITLE
Autostart/Autorun

### ISSUE THREAD

**Issue by Danny1206** [AntonyCorbett/OnlyR#72]
Is it possible that the Only-R starts automatically with Windows 10. The recording works with the start in the background. Then the recording should also be saved when Windows is closed, without pressing the Stop button.

**Comment by lazer321** [comment]
@Danny1206,

You can use task scheduler to run OnlyR on startup. Alternatively, you can open a file explorer window and type:  shell:startup  in the location bar and that will take you to that user account's startup folder. Any shortcuts placed in that folder will run when the user logs in. I believe there are settings in OnlyR to run it minimized, start recording immediately, and save the recording upon closing.

I hope these tips have been helpful.

YB,
            - K McCabe.

**Comment by AntonyCorbett** [comment]
@Danny1206 Please take a look at the description of the options in the wiki. There are a couple of settings that are useful here.

**Comment by Danny1206** [comment]
Yes, everything works as described. But if you exit Windows 10 and forget to press the Stop button in Only-R, no recording will be saved. It would be nice if the recording were also created automatically.

**Comment by AntonyCorbett** [comment]
Use the "Allow close when recording" option

**Comment by Danny1206** [comment]
I tried the option. Exiting the app works, but after restarting the PC there is no recording

**Comment by AntonyCorbett** [comment]
@Danny1206 - you're right, I must have been thinking of something else.
