### ISSUE TITLE
Recording device

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyR#79]
Hi! I ask you if it will be possible to add the computer's audio itself as a recording device. It is becoming necessary to record from Zoom and ONLY R only accepts microphones or input lines as recording devices. 
Best regards

**Comment by kq5m9** [comment]
Hi @gonzo041,
One option, depending on your configuration, might be to enable Stereo Mix in the input section of your computer's Sound settings. Another option might be to use either a hardware or software audio patch cord.
Hope that helps.
YB,
   - Kev.

**Comment by AntonyCorbett** [comment]
@gonzo041 Now available in the latest pre-release
