### ISSUE TITLE
"Portable" installation

### ISSUE THREAD

**Issue by daveloyall** [AntonyCorbett/OnlyR#80]
**Is your feature request related to a problem? Please describe.**
I don't want to run your installer `.exe` file with elevated priveleges.

**Describe the solution you'd like**
I'd like a `.zip` file on the Github **Releases** page which I can just unzip to some directory and run the program from there without clicking Yes on any UAC prompt.  I can create my own start menu shortcut (but I probably won't).

**Describe alternatives you've considered**
I considered just running your installer with elevated permissions.  I also considered building it from source.

**Additional context**
This project looks just like what I want.  As simple tool for a simple job.  Good work!  Thank you!

**Comment by AntonyCorbett** [comment]
@daveloyall Thanks for your feedback. The latest pre-release contains a portable archive. It does require the .NET 5 runtime
