### ISSUE TITLE
Feature Request - WAV output

### ISSUE THREAD

**Issue by Mister-Curious** [AntonyCorbett/OnlyR#84]
**Is your feature request related to a problem? Please describe.**
Lack of quality from MP3s. 

**Describe the solution you'd like**
Is there any chance you could add .wav file as an output file?

**Describe alternatives you've considered**
none

**Additional context**
Thanks !

**Comment by kubinka0505** [comment]
need this asap

**Comment by AntonyCorbett** [comment]
@Mister-Curious - please see the latest pre-release. This includes WAV support.
