### ISSUE TITLE
Saving Records not in sub-folders

### ISSUE THREAD

**Issue by edonadeo** [AntonyCorbett/OnlyR#85]
Hello brother,

By default, OnlyR stores recordings in the MyDocuments\OnlyR folder, and within date-specific sub-folders.
Is it possible to save them only in a main folder?
To have a better overview of all the records. We record only the talk and and it is easer to have them not in subfolders. We are using also a lifetime for recordings. (1 month). So we have only few files.

Thanks for your support.

BR,
Emanuel

**Comment by AntonyCorbett** [comment]
@edonadeo Sorry for the late reply! I've looked at this, but the purge function, which automatically deletes old files, uses folder naming by date. To store all the recordings in a single folder would involve the reworking of the purge function. It seems like too much effort for a small benefit. Sorry! Antony
