### ISSUE TITLE
How to capture audio

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyR#87]
Hi Antony

Scenario: We want to record our meeting audio using OnlyR. 

At the moment our Media PC is sending audio out to our mixer (songs etc), and receiving audio back (microphones) so that we can send the PC audio AND the received audio out to ZOOM. (We use the Share PC Audio feature of ZOOM).  We also send audio from ZOOM participant commenters out to the mixer as well so the in-person friends can hear their comments. 

When I enable OnlyR and use the loop capture option, we are getting the audio from the PC media, and the ZOOM comments, but *not* the received audio from the mixer. If I try to select "listen" (monitor) in the sound settings we get nasty, really nasty feedback.  There is no option (that I can see) in OnlyR "recording device" to capture the audio that ZOOM is getting and sending back from hybrid comments. 

Please do you have any suggestions on what we can do to capture ALL audio, from the PC, ZOOM and mixer simultaneously to capture all audio to record?

We did use our other connected PC (ZOOM attendant PC) to record audio from ZOOM as it was getting everything, but we were getting an echo feedback when we wanted to send the chime/bell from OnlyT to the mixer if a student talk went overtime. 

I hope that makes sense. I know I must be doing something wrong but at the moment the answer is eluding me. 
I really value your thoughts.
Kind regards
Simon

**Comment by kq5m9** [comment]
Hi #Chipperchap,

I am not Antony. But if it's any use to you, I can tell you what we have found successful.

In sound settings, set the output device to Speakers; the input device to Line In.
In Zoom, click the up arrow next to the mute/unmute button and set both the microphone and speaker to Same as System.
In OnlyR, set the audio source to Line In.

This way the computer audio from both JW Library (songs/videos) and Zoom commenters goes out the speaker connection on the computer to an input channel on the mixer. Of course, all Zoom participants would have to be muted during the meeting when they are not commenting.

The audio output from the mixer (which is the same as what is heard in the auditorium) goes into the computer on Line In from the mixer's output and out to Zoom and is also recorded by OnlyR. Zoom is unmuted during the meeting so all zoom participants can hear what the in-person audience hears

The only possible audio loop is during Zoom comments and Zoom has echo cancellation to prevent feedback there.

I hope this may have been of help.

YB,
       - Kev.

**Comment by Chipperchap** [comment]
> I hope this may have been of help.

Thanks Kev. 👍
I have decided to record all audio using our A/V PC instead of the attendant PC. I am using the equivalent to the "Line-in" source and it is now working for me. My next challenge is getting it to record at a level better than 57.  The slider is greyed out. I will keep looking at it to try figure it out. 😄

**Comment by kq5m9** [comment]
One final comment, if I may, Simon...

When I said "what we have found successful", it was in reference to what we used to do. Currently, we are not recording meetings. I don't know if that was a local decision or if it came from another source. So I might suggest that you may wish to double check with your local BoE, just to be sure. 

I wish you the best, my brother. 😁

    - Kev.

**Comment by Chipperchap** [comment]
> double check with your local BoE, just to be sure.

Yes, no problem. Thanks for your caution. 👍
