### ISSUE TITLE
Automatically record within a certain time slot

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyR#9]
Ability of OnlyR to auto-record at pre-selected time intervals.  Likely two slots for each user congregation.  Ability to select 'Auto' or 'Manual' recording of meetings.

So if a meeting starts at 7:00pm and finishes at 8:45pm, it is pretty safe to assume that a recording of 105 minutes will 'catch' most of the meeting (115 minutes would allow for letters read and special announcements).  

Why? One less thing for the booth operator to remember to do (recording of the meetings)  Was great with SoundBox that it would auto record once opening song was played and background music was started at the conclusion of the meeting.

**Comment by AntonyCorbett** [comment]
@Chipperchap - It's possible to use the Windows Task Scheluder to configure this (although this would require some knowledge of that tool), so it's unlikely to be a high priority item.

**Comment by Chipperchap** [comment]
I am not familiar with WTS but did trial it (with the help of Google) and got it working.  Is there also a way to use WTS to stop the app / .exc at a given time?

**Comment by Chipperchap** [comment]
Before I start learning 'TaskKill' please do you happen to know if OnlyR will fade out the current recording and 'save' if it is 'killed' or stopped via WTS, or might it just stop and not save?

**Comment by AntonyCorbett** [comment]
@Chipperchap - taskkill closes an application gracefully unless you use the /f parameter which forces an application to close.

**Comment by Chipperchap** [comment]
Ok, so I tried:
taskkilll /IM OnlyR.exe
...and that doesn't work.  The red X also won't close the program while it is recording (which is a good thing).  
I don't want to use: 
taskkill /F /IM onlyr.exe
...because I have found that it kills the program without saving the recording.
So I think I need to get TaskKill to stop the recording first then kill the process. Please, do you happen to know the formula for that? :-)

**Comment by AntonyCorbett** [comment]
@Chipperchap - ah yes, I didn't think of that. You'd need to use something like AutoHotKey to create a script that would end the recording before closing the app. It's getting messy. Th easiest solution is for me to add an option that allows the app to be closed while recording - and when this happens the recording would be faded out and that app closed gracefully.

**Comment by Chipperchap** [comment]
Great!  That sounds like a workable solution. :-)
Thank you for your kindly consideration of these details.

**Comment by AntonyCorbett** [comment]
@Chipperchap - new option "Allow close when recording" is now available.

**Comment by AntonyCorbett** [comment]
Closing because the required function can be provided by Windows task scheduler.
